=== AlanruoyuLiu/PolyU_MScST/COMP5323/Assignment/Q3_StarChefs/show.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:t="http://qingpei.me/COMP5323"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://qingpei.me/COMP5323"
elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="show">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string" >
        <xs:element ref="t:episode" maxOccurs="unbounded" >
        <xs:element ref="t:star_chef" minOccurs="4"
        maxOccurs="unbounded" />
        <xs:element ref="t:ingredient" maxOccurs="unbounded" >
        <xs:element ref="t:challenger" maxOccurs="unbounded" >
      </xs:sequence>
    </xs:complexType>
    <xs:key name="episode_id">
      <xs:selector xpath="t:episode" >
      <xs:field xpath="t:number" >
    </xs:key>
    <xs:key name="chef_id">
      <xs:selector xpath="t:star_chef" >
      <xs:field xpath="t:name" >
    </xs:key>
    <xs:key name="challenger_id">
      <xs:selector xpath="t:challenger" >
      <xs:field xpath="t:name" >
      <xs:field xpath="t:restaurant" >
    </xs:key>
    <xs:key name="ingredient_id">
      <xs:selector xpath="t:ingredient" >
      <xs:field xpath="t:id" >
    </xs:key>
    <xs:keyref name="episode_idref" refer="t:episode_id">
      <xs:selector xpath="t:star_chef/t:episode_appeared" />
      <xs:field xpath="@ref" >
    </xs:keyref>
    <xs:keyref name="chef_idref" refer="t:chef_id">
      <xs:selector xpath="t:episode/t:star_chef|t:episode/t:challenged_chef" />
      <xs:field xpath="@ref" >
    </xs:keyref>
    <xs:keyref name="challenger_idref" refer="t:challenger_id">
      <xs:selector xpath="t:episode/t:challenger" />
      <xs:field xpath="@key1" >
      <xs:field xpath="@key2" >
    </xs:keyref>
    <xs:keyref name="ingredient_idref" refer="t:ingredient_id">
      <xs:selector xpath="t:episode/t:ingredient" />
      <xs:field xpath="@ref" >
    </xs:keyref>
    <xs:unique name="ingredient">
      <xs:selector xpath="t:episode/t:ingredient" />
      <xs:field xpath="@ref" >
    </xs:unique>
  </xs:element>
  <xs:element name="episode">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="t:episodeType" >
      </xs:complexContent>
    </xs:complexType>
    <xs:key name="judge_id">
      <xs:selector xpath="t:judge" >
      <xs:field xpath="t:name" >
    </xs:key>
    <xs:key name="star_id">
      <xs:selector xpath="t:star_chef|t:challenged_chef" >
      <xs:field xpath="@ref" >
    </xs:key>
    <xs:unique name="judge_name">
      <xs:selector xpath="t:judge" >
      <xs:field xpath="t:name" >
    </xs:unique>
  </xs:element>
  <xs:complexType name="episodeType">
    <xs:sequence>
      <xs:element name="number" type="xs:positiveInteger" >
      <xs:element name="star_chef" type="t:refType" minOccurs="3"
      maxOccurs="3" />
      <xs:element name="challenged_chef" type="t:refType" >
      <xs:element name="challenger" type="t:doubleRefType" >
      <xs:element name="ingredient" type="t:refType" >
      <xs:element name="judge" minOccurs="4" maxOccurs="4">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" type="xs:string" >
            <xs:element name="score_star" type="t:scoreType" >
            <xs:element name="score_challenger"
            type="t:scoreType" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="winner_is_challenger" type="xs:boolean" >
    </xs:sequence>
  </xs:complexType>
  <xs:element name="star_chef">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="t:personType">
          <xs:sequence>
            <xs:element name="episode_appeared" type="t:refType"
            maxOccurs="unbounded" />
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="personType">
    <xs:sequence>
      <xs:element name="name" type="xs:string" >
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="refType">
    <xs:attribute name="ref" use="required" >
  </xs:complexType>
  <xs:element name="ingredient" type="t:ingredientType" >
  <xs:complexType name="ingredientType">
    <xs:sequence>
      <xs:element name="id" type="xs:positiveInteger" >
      <xs:element name="name" type="xs:string" >
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="challengerType">
    <xs:complexContent>
      <xs:extension base="t:personType">
        <xs:sequence>
          <xs:element name="restaurant" type="xs:string" >
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="challenger" type="t:challengerType" >
  <xs:complexType name="doubleRefType">
    <xs:attribute name="key1" use="required" >
    <xs:attribute name="key2" use="required" >
  </xs:complexType>
  <xs:complexType name="scoreType">
    <xs:sequence>
      <xs:element name="taste">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0" >
            <xs:maxInclusive value="20" >
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="appearance">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0" >
            <xs:maxInclusive value="20" >
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== AlanruoyuLiu/PolyU_MScST/COMP5323/Assignment/Q3_StarChefs/show.xml
<?xml version="1.0" encoding="utf-8"?>
<t:show xmlns:t="http://qingpei.me/COMP5323"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://qingpei.me/COMP5323 show.xsd">
  <t:name>Star Chef with Ma</t:name>
  <t:episode>
    <t:number>3</t:number>
    <t:star_chef ref="Llian" >
    <t:star_chef ref="Mosquay" >
    <t:star_chef ref="Creit" >
    <t:challenged_chef ref="Thermosy" >
    <t:challenger key1="Setin" key2="Café Caliblini" >
    <t:ingredient ref="1" >
    <t:judge>
      <t:name>Darsrad</t:name>
      <t:score_star>
        <t:taste>8</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_star>
      <t:score_challenger>
        <t:taste>16</t:taste>
        <t:appearance>6</t:appearance>
      </t:score_challenger>
    </t:judge>
    <t:judge>
      <t:name>Rodnray</t:name>
      <t:score_star>
        <t:taste>8</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_star>
      <t:score_challenger>
        <t:taste>16</t:taste>
        <t:appearance>6</t:appearance>
      </t:score_challenger>
    </t:judge>
    <t:judge>
      <t:name>Lerys</t:name>
      <t:score_star>
        <t:taste>8</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_star>
      <t:score_challenger>
        <t:taste>16</t:taste>
        <t:appearance>6</t:appearance>
      </t:score_challenger>
    </t:judge>
    <t:judge>
      <t:name>Enthrpol</t:name>
      <t:score_star>
        <t:taste>8</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_star>
      <t:score_challenger>
        <t:taste>16</t:taste>
        <t:appearance>6</t:appearance>
      </t:score_challenger>
    </t:judge>
    <t:winner_is_challenger>true</t:winner_is_challenger>
  </t:episode>
  <t:episode>
    <t:number>2</t:number>
    <t:star_chef ref="Llian" >
    <t:star_chef ref="Mosquay" >
    <t:star_chef ref="Creit" >
    <t:challenged_chef ref="Serad" >
    <t:challenger key1="Thermosy" key2="Triage Fish n Chips" >
    <t:ingredient ref="2" >
    <t:judge>
      <t:name>Darsrad</t:name>
      <t:score_star>
        <t:taste>8</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_star>
      <t:score_challenger>
        <t:taste>16</t:taste>
        <t:appearance>6</t:appearance>
      </t:score_challenger>
    </t:judge>
    <t:judge>
      <t:name>Rodnray</t:name>
      <t:score_star>
        <t:taste>8</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_star>
      <t:score_challenger>
        <t:taste>16</t:taste>
        <t:appearance>6</t:appearance>
      </t:score_challenger>
    </t:judge>
    <t:judge>
      <t:name>Lerys</t:name>
      <t:score_star>
        <t:taste>8</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_star>
      <t:score_challenger>
        <t:taste>16</t:taste>
        <t:appearance>6</t:appearance>
      </t:score_challenger>
    </t:judge>
    <t:judge>
      <t:name>Enthrpol</t:name>
      <t:score_star>
        <t:taste>8</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_star>
      <t:score_challenger>
        <t:taste>16</t:taste>
        <t:appearance>6</t:appearance>
      </t:score_challenger>
    </t:judge>
    <t:winner_is_challenger>true</t:winner_is_challenger>
  </t:episode>
  <t:episode>
    <t:number>1</t:number>
    <t:star_chef ref="Llian" >
    <t:star_chef ref="Serad" >
    <t:star_chef ref="Creit" >
    <t:challenged_chef ref="Delore" >
    <t:challenger key1="Mosquay" key2="China Duck" >
    <t:ingredient ref="3" >
    <t:judge>
      <t:name>Darsrad</t:name>
      <t:score_star>
        <t:taste>8</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_star>
      <t:score_challenger>
        <t:taste>9</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_challenger>
    </t:judge>
    <t:judge>
      <t:name>Rodnray</t:name>
      <t:score_star>
        <t:taste>8</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_star>
      <t:score_challenger>
        <t:taste>9</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_challenger>
    </t:judge>
    <t:judge>
      <t:name>Lerys</t:name>
      <t:score_star>
        <t:taste>8</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_star>
      <t:score_challenger>
        <t:taste>9</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_challenger>
    </t:judge>
    <t:judge>
      <t:name>Enthrpol</t:name>
      <t:score_star>
        <t:taste>8</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_star>
      <t:score_challenger>
        <t:taste>9</t:taste>
        <t:appearance>9</t:appearance>
      </t:score_challenger>
    </t:judge>
    <t:winner_is_challenger>true</t:winner_is_challenger>
  </t:episode>
  <t:star_chef>
    <t:name>Serad</t:name>
    <t:episode_appeared ref="1" >
    <t:episode_appeared ref="2" >
    <t:episode_appeared ref="3" >
  </t:star_chef>
  <t:star_chef>
    <t:name>Llian</t:name>
    <t:episode_appeared ref="1" >
    <t:episode_appeared ref="2" >
    <t:episode_appeared ref="3" >
  </t:star_chef>
  <t:star_chef>
    <t:name>Creit</t:name>
    <t:episode_appeared ref="1" >
    <t:episode_appeared ref="2" >
    <t:episode_appeared ref="3" >
  </t:star_chef>
  <t:star_chef>
    <t:name>Delore</t:name>
    <t:episode_appeared ref="1" >
  </t:star_chef>
  <t:star_chef>
    <t:name>Mosquay</t:name>
    <t:episode_appeared ref="2" >
  </t:star_chef>
  <t:star_chef>
    <t:name>Thermosy</t:name>
    <t:episode_appeared ref="3" >
  </t:star_chef>
  <t:ingredient>
    <t:id>1</t:id>
    <t:name>Grilled Cheese</t:name>
  </t:ingredient>
  <t:ingredient>
    <t:id>2</t:id>
    <t:name>Orange Juice</t:name>
  </t:ingredient>
  <t:ingredient>
    <t:id>3</t:id>
    <t:name>French Fries</t:name>
  </t:ingredient>
  <t:challenger>
    <t:name>Setin</t:name>
    <t:restaurant>Café Caliblini</t:restaurant>
  </t:challenger>
  <t:challenger>
    <t:name>Mosquay</t:name>
    <t:restaurant>China Duck</t:restaurant>
  </t:challenger>
  <t:challenger>
    <t:name>Thermosy</t:name>
    <t:restaurant>Triage Fish n Chips</t:restaurant>
  </t:challenger>
</t:show>
